### PR TITLE
Examples for advanced references with Biber (yearauthor)

### PR DESCRIPTION
**Pull request by habernal**
Some communities use yearauthor style for citations. Added examples and a possible biblatex configuration with Biber+natbib, disabled by default.

### CODE REVIEW

**Comment by TeXhackse** [comment]
Oh and the Template itself is already using biber. Biber is the default backend for BibLaTeX since years…

**Comment by habernal** [comment]
Fair enough, the default template is maybe not the best place. A wiki-page or similar would definitely help, so I can point my students there.

**Comment by TeXhackse** [comment]
I did note like an extra directory because it would not be structured and hard to find. 
We still could enable the wiki in here, can't we? The wiki would allow us to structure the user contributed content. 

I just lack the permissions like I do für #331

**Comment by TeXhackse** [comment]
https://github.com/tudace/tuda_latex_templates/wiki/Bibliography

**Comment by habernal** [comment]
Thanks @TeXhackse , closing this PR.

**Pull request closed without merging**
